[theme]
primaryColor = "#2979ff"
backgroundColor = "#0d1321"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "error"

[server]
headless = true
runOnSave = true
